// Mocks generated by Mockito 5.4.6 from annotations
// in insurance_claim_app/test/features/claims/presentation/screen/claim_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:insurance_claim_app/features/claims/domain/entities/claim_entity.dart'
    as _i5;
import 'package:insurance_claim_app/features/claims/domain/repositories/claim_repository.dart'
    as _i2;
import 'package:insurance_claim_app/features/claims/domain/usecases/get_claim.dart'
    as _i3;
import 'package:insurance_claim_app/features/claims/domain/usecases/search_claim.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClaimRepository_0 extends _i1.SmartFake
    implements _i2.ClaimRepository {
  _FakeClaimRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetClaim].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetClaim extends _i1.Mock implements _i3.GetClaim {
  MockGetClaim() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClaimRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeClaimRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ClaimRepository);

  @override
  _i4.Future<List<_i5.ClaimEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.ClaimEntity>>.value(
              <_i5.ClaimEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ClaimEntity>>);
}

/// A class which mocks [SearchClaim].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchClaim extends _i1.Mock implements _i6.SearchClaim {
  MockSearchClaim() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClaimRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeClaimRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ClaimRepository);

  @override
  _i4.Future<List<_i5.ClaimEntity>> call(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#call, [keyword]),
            returnValue: _i4.Future<List<_i5.ClaimEntity>>.value(
              <_i5.ClaimEntity>[],
            ),
          )
          as _i4.Future<List<_i5.ClaimEntity>>);
}
